classDiagram
    namespace io.cuttlefish {
        class MainKt {
            +mainjava.lang.Object (java.lang.String[], kotlin.coroutines.Continuation<? super kotlin.Unit>)
            +printUsagevoid ()
            +access$throwRuntimeError-o2CYthUjava.lang.Object (io.cuttlefish.components.Cpu, java.lang.Exception, short, int, kotlin.coroutines.Continuation)
            +access$handleRunjava.lang.Object (java.util.List, kotlin.coroutines.Continuation)
            +printHexDump-CLC0ZwA$defaultjava.lang.Object (io.cuttlefish.components.MemoryBus, short, int, boolean, boolean, kotlin.coroutines.Continuation, int, java.lang.Object)
            +access$handleCompileAndRunjava.lang.Object (java.util.List, kotlin.coroutines.Continuation)
            +mainvoid (java.lang.String[])
            +access$runCpuSafely-gsW5C1kjava.lang.Object (io.cuttlefish.components.Cpu, io.cuttlefish.components.MemoryBus, boolean, short, int, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation)
            +access$generateDebugFiles-qXxezQojava.lang.Object (java.lang.String, short, java.util.List, java.util.Map, io.cuttlefish.components.Cpu, io.cuttlefish.components.MemoryBus, kotlin.coroutines.Continuation)
            +access$handleHexDumpFilejava.lang.Object (java.util.List, kotlin.coroutines.Continuation)
            +loadConfigvoid ()
            +access$handleRunOsjava.lang.Object (java.util.List, kotlin.coroutines.Continuation)
            +printHexDump-CLC0ZwAjava.lang.Object (io.cuttlefish.components.MemoryBus, short, int, boolean, boolean, kotlin.coroutines.Continuation<? super java.lang.String>)
            +access$handleBuildjava.lang.Object (java.util.List, kotlin.coroutines.Continuation)
        }
        class ExecutionTestBase
    }
