classDiagram
    namespace io.cuttlefish.parsing {
        class ImmediateToken {
            +int hashCode()
            +String getLexeme()
            +String component2()
            +int component3()
            +int component4()
            +boolean equals(Object)
            +ImmediateToken copy(short, String, int, int)
            +int getLine()
            +short component1()
            +String toString()
            +int getColumn()
            +short getValue()
        }
        class MnemonicToken {
            +String component1()
            +int hashCode()
            +String getLexeme()
            +int component3()
            +boolean equals(Object)
            +int getLine()
            +MnemonicToken copy(String, int, int)
            +String toString()
            +int getColumn()
            +int component2()
        }
        class SkipToken {
            +SkipToken INSTANCE
            +String getLexeme()
            +int getLine()
            +int getColumn()
        }
        class EndOfLineToken {
            +EndOfLineToken INSTANCE
            +String getLexeme()
            +int getLine()
            +int getColumn()
        }
        class Parser {
            +getSymbolTablejava.util.Map<java.lang.String, java.lang.Short> ()
            +getImportsjava.util.List<java.lang.String> ()
            +getRelocationsjava.util.List<io.cuttlefish.linking.RelocationTable> ()
            +getFilejava.io.File ()
            +getBaseAddressshort ()
            +decodejava.util.List<io.cuttlefish.Instruction> ()
        }
        class TokenReader {
            +peekio.cuttlefish.parsing.Token ()
            +nextRegio.cuttlefish.RegisterType ()
            +hasNextboolean ()
            +nextArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +setIndexvoid (int)
            +getTokensjava.util.List<io.cuttlefish.parsing.Token> ()
            +getIndexint ()
            +nextStringjava.lang.String ()
        }
        class Token {
            +String getLexeme()
            +int getLine()
            +int getColumn()
        }
        class LabelDefToken {
            +String component1()
            +int hashCode()
            +String getLexeme()
            +String component2()
            +int component3()
            +int component4()
            +boolean equals(Object)
            +LabelDefToken copy(String, String, int, int)
            +int getLine()
            +String getLabelName()
            +String toString()
            +int getColumn()
        }
        class LexerException {
            +int getLine()
            +int getColumn()
        }
        class SyntaxException
        class SyntaxRegistry {
            +List getRules()
        }
        class SourceLine {
            +int hashCode()
            +String component2()
            +boolean equals(Object)
            +String toString()
            +int getLineNumber()
            +int component1()
            +String getRawText()
            +SourceLine copy(int, String)
        }
        class RegisterToken {
            +copy$defaultio.cuttlefish.parsing.RegisterToken (io.cuttlefish.parsing.RegisterToken, io.cuttlefish.RegisterType, java.lang.String, int, int, int, java.lang.Object)
            +toStringjava.lang.String ()
            +getLineint ()
            +copyio.cuttlefish.parsing.RegisterToken (io.cuttlefish.RegisterType, java.lang.String, int, int)
            +equalsboolean (java.lang.Object)
            +component2java.lang.String ()
            +getRegisterNameio.cuttlefish.RegisterType ()
            +getColumnint ()
            +getLexemejava.lang.String ()
            +component1io.cuttlefish.RegisterType ()
            +component3int ()
            +hashCodeint ()
            +component4int ()
        }
        class CompilationException {
            +String getFileName()
            +String getErrorMessage()
            +SourceLine getSourceLine()
        }
        class StringLiteralToken {
            +String component1()
            +int hashCode()
            +StringLiteralToken copy(String, String, int, int)
            +String getLexeme()
            +String component2()
            +int component3()
            +int component4()
            +boolean equals(Object)
            +String getText()
            +int getLine()
            +String toString()
            +int getColumn()
        }
        class Lexer {
            +List tokenise()
        }
        class StatementRegistryKt
        class SymbolReferenceToken {
            +String component1()
            +int hashCode()
            +String getLexeme()
            +String component2()
            +int component3()
            +int component4()
            +boolean equals(Object)
            +String getSymbolName()
            +int getLine()
            +SymbolReferenceToken copy(String, String, int, int)
            +String toString()
            +int getColumn()
        }
        class StatementRegistry {
            +StatementRegistry INSTANCE
            +registervoid (java.lang.String, kotlin.jvm.functions.Function3<? super io.cuttlefish.parsing.TokenReader, ? super java.lang.Integer, ? super java.lang.Integer, ? extends io.cuttlefish.parsing.syntaxTree.Statement>)
            +getBuildersjava.util.Map<java.lang.String, kotlin.jvm.functions.Function3<io.cuttlefish.parsing.TokenReader, java.lang.Integer, java.lang.Integer, io.cuttlefish.parsing.syntaxTree.Statement>> ()
        }
        class TokenRule {
            +MatchResult match(String, int, int, int)
        }
    }
    namespace io.cuttlefish.parsing.macros {
        class MacroSub {
            +getRCio.cuttlefish.RegisterType ()
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroClr {
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroRet {
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroBne {
            +getTargetio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroMov {
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroSubi {
            +getImmio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroPush {
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroSyscall {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroMovi {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroHalt {
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroLli {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroOr {
            +getRCio.cuttlefish.RegisterType ()
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroAnd {
            +getRCio.cuttlefish.RegisterType ()
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroPop {
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroCall {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class MacroNot {
            +getScopejava.lang.String ()
            +getRAio.cuttlefish.RegisterType ()
            +getLineint ()
            +getRBio.cuttlefish.RegisterType ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
    }
    namespace io.cuttlefish.parsing.syntaxTree {
        class RRRStatement {
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getR3io.cuttlefish.RegisterType ()
            +getColint ()
            +getOpjava.lang.String ()
            +getR2io.cuttlefish.RegisterType ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class DirectiveSpace {
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class ParserContext {
            +String getCurrentGlobalScope()
            +List getImports()
            +void setCurrentGlobalScope(String)
            +short getBaseAddress()
            +Map getSymbolTable()
            +String resolveScopedName(String)
            +List getRelocations()
        }
        class Argument
        class RRIStatement {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getOpjava.lang.String ()
            +getR2io.cuttlefish.RegisterType ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class RIStatement {
            +getArgio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getR1io.cuttlefish.RegisterType ()
            +getLineint ()
            +getColint ()
            +getOpjava.lang.String ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class DirectiveFillString {
            +getScopejava.lang.String ()
            +getTextjava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class ImmArg {
            +int hashCode()
            +boolean equals(Object)
            +ImmArg copy(short)
            +short component1()
            +String toString()
            +short getValue()
        }
        class SymArg {
            +String component1()
            +int hashCode()
            +int component3()
            +boolean equals(Object)
            +int getLine()
            +String getName()
            +SymArg copy(String, int, int)
            +int getCol()
            +String toString()
            +int component2()
        }
        class Statement {
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +setScopevoid (java.lang.String)
            +getSizeint ()
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
        class DirectiveFillImmediate {
            +getValueShortio.cuttlefish.parsing.syntaxTree.Argument ()
            +getScopejava.lang.String ()
            +getLineint ()
            +getColint ()
            +getSizeint ()
            +setScopevoid (java.lang.String)
            +generatejava.util.List<io.cuttlefish.Instruction> (io.cuttlefish.parsing.syntaxTree.ParserContext, short)
        }
    }
    namespace io.cuttlefish.parsing.rules {
        class SkipTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class LabelTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class RegisterTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class SymbolReferenceTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class EndOfLineTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class MnemonicTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class StringLiteralTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
        class ImmediateTokenRule {
            +matchio.cuttlefish.parsing.TokenRule$MatchResult (java.lang.String, int, int, int)
        }
    }
    namespace io.cuttlefish.linking {
        class ObjectExcreter {
            +File getFile()
            +ObjectFile generate()
        }
        class Header {
            +Header$Companion Companion
            +Companion Companion
            +getSectionSize-Mh2AYegshort ()
            +getRelocationCount-Mh2AYegshort ()
            +component1java.lang.String ()
            +component4-Mh2AYegshort ()
            +copy-DqvSWFQio.cuttlefish.linking.Header (java.lang.String, short, short, short)
            +getSymbolCount-Mh2AYegshort ()
            +component3-Mh2AYegshort ()
            +toStringjava.lang.String ()
            +equalsboolean (java.lang.Object)
            +write$Self$io_cuttlefish_compilervoid (io.cuttlefish.linking.Header, kotlinx.serialization.encoding.CompositeEncoder, kotlinx.serialization.descriptors.SerialDescriptor)
            +component2-Mh2AYegshort ()
            +hashCodeint ()
            +copy-DqvSWFQ$defaultio.cuttlefish.linking.Header (io.cuttlefish.linking.Header, java.lang.String, short, short, short, int, java.lang.Object)
            +getFileNamejava.lang.String ()
        }
        class ObjectFile {
            +ObjectFile$Companion Companion
            +copy$defaultio.cuttlefish.linking.ObjectFile (io.cuttlefish.linking.ObjectFile, io.cuttlefish.linking.Header, java.util.List, java.util.List, java.util.List, int, java.lang.Object)
            +getPayloadjava.util.List<kotlin.UShort> ()
            +toStringjava.lang.String ()
            +component1io.cuttlefish.linking.Header ()
            +copyio.cuttlefish.linking.ObjectFile (io.cuttlefish.linking.Header, java.util.List<kotlin.UShort>, java.util.List<io.cuttlefish.linking.SymbolTable>, java.util.List<io.cuttlefish.linking.RelocationTable>)
            +equalsboolean (java.lang.Object)
            +component2java.util.List<kotlin.UShort> ()
            +getSymbolTablesjava.util.List<io.cuttlefish.linking.SymbolTable> ()
            +access$get$childSerializers$cpkotlin.Lazy[] ()
            +write$Self$io_cuttlefish_compilervoid (io.cuttlefish.linking.ObjectFile, kotlinx.serialization.encoding.CompositeEncoder, kotlinx.serialization.descriptors.SerialDescriptor)
            +component4java.util.List<io.cuttlefish.linking.RelocationTable> ()
            +component3java.util.List<io.cuttlefish.linking.SymbolTable> ()
            +hashCodeint ()
            +getHeaderio.cuttlefish.linking.Header ()
            +getRelocationTablejava.util.List<io.cuttlefish.linking.RelocationTable> ()
        }
        class RelocationTable {
            +RelocationTable$Companion Companion
            +getOffset-Mh2AYegshort ()
            +write$Self$io_cuttlefish_compilervoid (io.cuttlefish.linking.RelocationTable, kotlinx.serialization.encoding.CompositeEncoder, kotlinx.serialization.descriptors.SerialDescriptor)
            +getTypeio.cuttlefish.linking.RelocationType ()
            +toStringjava.lang.String ()
            +getNamejava.lang.String ()
            +equalsboolean (java.lang.Object)
            +component2java.lang.String ()
            +component3io.cuttlefish.linking.RelocationType ()
            +access$get$childSerializers$cpkotlin.Lazy[] ()
            +hashCodeint ()
            +component1-Mh2AYegshort ()
            +copy-_TFR7lA$defaultio.cuttlefish.linking.RelocationTable (io.cuttlefish.linking.RelocationTable, short, java.lang.String, io.cuttlefish.linking.RelocationType, int, java.lang.Object)
            +copy-_TFR7lAio.cuttlefish.linking.RelocationTable (short, java.lang.String, io.cuttlefish.linking.RelocationType)
        }
        class LinkerKt {
            +getMainFsLjava.io.File ()
            +getMathsFsLjava.io.File ()
            +mainvoid (java.lang.String[])
            +mainjava.lang.Object (kotlin.coroutines.Continuation<? super kotlin.Unit>)
        }
        class LinkerException {
            +String getFileAbsolutePath()
            +String getSymbolName()
            +String getErrorMessage()
        }
        class RelocationType {
            +RelocationType$Companion Companion
            +RelocationType ABS_LUI
            +RelocationType REL_7
            +RelocationType ABS_LLI
            +RelocationType ABS_16
            +getEntrieskotlin.enums.EnumEntries<io.cuttlefish.linking.RelocationType> ()
            +access$get$cachedSerializer$delegate$cpkotlin.Lazy ()
            +valueOfio.cuttlefish.linking.RelocationType (java.lang.String)
            +valuesio.cuttlefish.linking.RelocationType[] ()
        }
        class Linker {
            +getGroupedByFilejava.util.Map<java.io.File, io.cuttlefish.linking.ObjectFile> ()
            +passOnejava.util.Map<java.lang.String, kotlin.UShort> ()
            +passTwokotlin.UShort[] (java.util.Map<java.lang.String, kotlin.UShort>)
        }
        class SymbolType {
            +SymbolType$Companion Companion
            +SymbolType Import
            +SymbolType Export
            +access$get$cachedSerializer$delegate$cpkotlin.Lazy ()
            +valuesio.cuttlefish.linking.SymbolType[] ()
            +valueOfio.cuttlefish.linking.SymbolType (java.lang.String)
            +getEntrieskotlin.enums.EnumEntries<io.cuttlefish.linking.SymbolType> ()
        }
        class SymbolTable {
            +SymbolTable$Companion Companion
            +getOffset-Mh2AYegshort ()
            +component1java.lang.String ()
            +component2io.cuttlefish.linking.SymbolType ()
            +write$Self$io_cuttlefish_compilervoid (io.cuttlefish.linking.SymbolTable, kotlinx.serialization.encoding.CompositeEncoder, kotlinx.serialization.descriptors.SerialDescriptor)
            +component3-Mh2AYegshort ()
            +toStringjava.lang.String ()
            +getNamejava.lang.String ()
            +equalsboolean (java.lang.Object)
            +copy-3IiRHeEio.cuttlefish.linking.SymbolTable (java.lang.String, io.cuttlefish.linking.SymbolType, short)
            +access$get$childSerializers$cpkotlin.Lazy[] ()
            +getTypeio.cuttlefish.linking.SymbolType ()
            +copy-3IiRHeE$defaultio.cuttlefish.linking.SymbolTable (io.cuttlefish.linking.SymbolTable, java.lang.String, io.cuttlefish.linking.SymbolType, short, int, java.lang.Object)
            +hashCodeint ()
        }
    }
    namespace io.cuttlefish {
        class HelpersKt {
            +toRegisterTypeio.cuttlefish.RegisterType (java.lang.String)
        }
        class Mnemonics {
            +Mnemonics And
            +Mnemonics Sw
            +Mnemonics Or
            +Mnemonics Bne
            +Mnemonics Mov
            +Mnemonics Not
            +Mnemonics Addi
            +Mnemonics Jalr
            +Mnemonics Nop
            +Mnemonics Pop
            +Mnemonics Call
            +Mnemonics Lli
            +Mnemonics Clr
            +Mnemonics Add
            +Mnemonics Ret
            +Mnemonics Syscall
            +Mnemonics Movi
            +Mnemonics Push
            +Mnemonics Lw
            +Mnemonics Halt
            +Mnemonics Beq
            +Mnemonics Nand
            +Mnemonics Lui
            +Mnemonics Sub
            +Mnemonics Subi
            +getEntrieskotlin.enums.EnumEntries<io.cuttlefish.Mnemonics> ()
            +valuesio.cuttlefish.Mnemonics[] ()
            +valueOfio.cuttlefish.Mnemonics (java.lang.String)
        }
        class TestKt {
            +void main()
        }
        class MagicValues {
            +MagicValues HPLI
            +MagicValues M_I10
            +MagicValues M_LB
            +MagicValues UNIT
            +MagicValues M_RA
            +MagicValues M_RB
            +MagicValues LNLI
            +MagicValues M_UB
            +MagicValues M_I7
            +MagicValues M_OC
            +MagicValues S_OC
            +MagicValues M_RC
            +MagicValues AONS
            +MagicValues S_RA
            +MagicValues S_RB
            +MagicValues HUI
            +MagicValues SBIT
            +MagicValues MXIT
            +getHexjava.lang.String ()
            +getValueshort ()
            +getEntrieskotlin.enums.EnumEntries<io.cuttlefish.MagicValues> ()
            +valuesio.cuttlefish.MagicValues[] ()
            +valueOfio.cuttlefish.MagicValues (java.lang.String)
        }
    }
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.ImmediateToken
    io.cuttlefish.parsing.ImmediateToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroSub
    io.cuttlefish.parsing.macros.MacroSub ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroSub ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroSub ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroSub ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.MnemonicToken
    io.cuttlefish.parsing.MnemonicToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.RRRStatement
    io.cuttlefish.parsing.syntaxTree.RRRStatement ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.RRRStatement ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.RRRStatement ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.RRRStatement ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.SkipTokenRule
    io.cuttlefish.parsing.rules.SkipTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.SkipTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.rules.SkipTokenRule ..> io.cuttlefish.parsing.SkipToken
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.DirectiveSpace
    io.cuttlefish.parsing.syntaxTree.DirectiveSpace ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.DirectiveSpace ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.DirectiveSpace ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.DirectiveSpace ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.syntaxTree.DirectiveSpace ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.SkipToken
    io.cuttlefish.parsing.SkipToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.syntaxTree.ParserContext ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.EndOfLineToken
    io.cuttlefish.parsing.EndOfLineToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.LabelDefToken
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.Lexer
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.MnemonicToken
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.CompilationException
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.LexerException
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.SyntaxException
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.EndOfLineToken
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.StatementRegistry
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.TokenReader
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.SourceLine
    io.cuttlefish.parsing.Parser ..> io.cuttlefish.parsing.Token
    io.cuttlefish.linking.ObjectExcreter ..> io.cuttlefish.parsing.Parser
    io.cuttlefish.linking.ObjectExcreter ..> io.cuttlefish.linking.SymbolType
    io.cuttlefish.linking.ObjectExcreter ..> io.cuttlefish.linking.Header
    io.cuttlefish.linking.ObjectExcreter ..> io.cuttlefish.linking.ObjectFile
    io.cuttlefish.linking.ObjectExcreter ..> io.cuttlefish.linking.SymbolTable
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.ImmediateToken
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.SymbolReferenceToken
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.StringLiteralToken
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.syntaxTree.SymArg
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.SyntaxException
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.TokenReader ..> io.cuttlefish.parsing.RegisterToken
    io.cuttlefish.parsing.syntaxTree.Argument ..> io.cuttlefish.parsing.syntaxTree.SymArg
    io.cuttlefish.parsing.syntaxTree.Argument ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroClr
    io.cuttlefish.parsing.macros.MacroClr ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroClr ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroClr ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroClr ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.RRIStatement
    io.cuttlefish.parsing.syntaxTree.RRIStatement ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.RRIStatement ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.RRIStatement ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.RRIStatement ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.RIStatement
    io.cuttlefish.parsing.syntaxTree.RIStatement ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.RIStatement ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.RIStatement ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.RIStatement ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroRet
    io.cuttlefish.parsing.macros.MacroRet ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroRet ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroRet ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroRet ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.LabelDefToken
    io.cuttlefish.parsing.LabelDefToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.linking.ObjectFile ..> io.cuttlefish.linking.Header
    io.cuttlefish.linking.ObjectFile ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.linking.ObjectFile ..> io.cuttlefish.linking.SymbolTable
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.LabelTokenRule
    io.cuttlefish.parsing.rules.LabelTokenRule ..> io.cuttlefish.parsing.LabelDefToken
    io.cuttlefish.parsing.rules.LabelTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.LabelTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.DirectiveFillString
    io.cuttlefish.parsing.syntaxTree.DirectiveFillString ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.DirectiveFillString ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.DirectiveFillString ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.DirectiveFillString ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroBne
    io.cuttlefish.parsing.macros.MacroBne ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroBne ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroBne ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroBne ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.RegisterTokenRule
    io.cuttlefish.parsing.rules.RegisterTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.RegisterTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.rules.RegisterTokenRule ..> io.cuttlefish.parsing.RegisterToken
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.SymbolReferenceTokenRule
    io.cuttlefish.parsing.rules.SymbolReferenceTokenRule ..> io.cuttlefish.parsing.SymbolReferenceToken
    io.cuttlefish.parsing.rules.SymbolReferenceTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.SymbolReferenceTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroMov
    io.cuttlefish.parsing.macros.MacroMov ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroMov ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroMov ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroMov ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroSubi
    io.cuttlefish.parsing.macros.MacroSubi ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroSubi ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroSubi ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroSubi ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.ImmediateTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.SymbolReferenceTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.LabelTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.MnemonicTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.SkipTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.StringLiteralTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.EndOfLineTokenRule
    io.cuttlefish.parsing.SyntaxRegistry ..> io.cuttlefish.parsing.rules.RegisterTokenRule
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroPush
    io.cuttlefish.parsing.macros.MacroPush ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroPush ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroPush ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroPush ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroSyscall
    io.cuttlefish.parsing.macros.MacroSyscall ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroSyscall ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroSyscall ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroSyscall ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.macros.MacroSyscall ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.EndOfLineTokenRule
    io.cuttlefish.parsing.rules.EndOfLineTokenRule ..> io.cuttlefish.parsing.EndOfLineToken
    io.cuttlefish.parsing.rules.EndOfLineTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.EndOfLineTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.syntaxTree.Argument <|-- io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.syntaxTree.ImmArg ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.RegisterToken
    io.cuttlefish.parsing.RegisterToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.syntaxTree.Argument <|-- io.cuttlefish.parsing.syntaxTree.SymArg
    io.cuttlefish.parsing.syntaxTree.SymArg ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.MnemonicTokenRule
    io.cuttlefish.parsing.rules.MnemonicTokenRule ..> io.cuttlefish.parsing.MnemonicToken
    io.cuttlefish.parsing.rules.MnemonicTokenRule ..> io.cuttlefish.Mnemonics
    io.cuttlefish.parsing.rules.MnemonicTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.MnemonicTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.CompilationException ..> io.cuttlefish.parsing.SourceLine
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.StringLiteralTokenRule
    io.cuttlefish.parsing.rules.StringLiteralTokenRule ..> io.cuttlefish.parsing.StringLiteralToken
    io.cuttlefish.parsing.rules.StringLiteralTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.StringLiteralTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroMovi
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.parsing.syntaxTree.SymArg
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.macros.MacroMovi ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroHalt
    io.cuttlefish.parsing.macros.MacroHalt ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroHalt ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroHalt ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroHalt ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.StringLiteralToken
    io.cuttlefish.parsing.StringLiteralToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.linking.RelocationTable ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.linking.LinkerKt ..> io.cuttlefish.linking.Linker
    io.cuttlefish.linking.LinkerKt ..> io.cuttlefish.linking.ObjectExcreter
    io.cuttlefish.linking.LinkerKt ..> io.cuttlefish.linking.ObjectFile
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroLli
    io.cuttlefish.parsing.macros.MacroLli ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroLli ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroLli ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroLli ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.macros.MacroLli ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.parsing.syntaxTree.SymArg
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.syntaxTree.Statement ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroOr
    io.cuttlefish.parsing.macros.MacroOr ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroOr ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroOr ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroOr ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.TokenRule <|.. io.cuttlefish.parsing.rules.ImmediateTokenRule
    io.cuttlefish.parsing.rules.ImmediateTokenRule ..> io.cuttlefish.parsing.ImmediateToken
    io.cuttlefish.parsing.rules.ImmediateTokenRule ..> io.cuttlefish.MagicValues
    io.cuttlefish.parsing.rules.ImmediateTokenRule ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.rules.ImmediateTokenRule ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.Lexer ..> io.cuttlefish.parsing.SyntaxRegistry
    io.cuttlefish.parsing.Lexer ..> io.cuttlefish.parsing.LexerException
    io.cuttlefish.parsing.Lexer ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.Lexer ..> io.cuttlefish.parsing.TokenRule
    io.cuttlefish.parsing.Lexer ..> io.cuttlefish.parsing.SkipToken
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate
    io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate ..> io.cuttlefish.parsing.syntaxTree.ImmArg
    io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroAnd
    io.cuttlefish.parsing.macros.MacroAnd ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroAnd ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroAnd ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroAnd ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.SymbolType
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.Header
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.ObjectFile
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.RelocationTable
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.LinkerException
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.linking.Linker ..> io.cuttlefish.linking.SymbolTable
    io.cuttlefish.parsing.Token <|.. io.cuttlefish.parsing.SymbolReferenceToken
    io.cuttlefish.parsing.SymbolReferenceToken ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroPop
    io.cuttlefish.parsing.macros.MacroPop ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroPop ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroPop ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroPop ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroSub
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.RRRStatement
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.DirectiveSpace
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroMovi
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroHalt
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.StringLiteralToken
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.TokenReader
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroClr
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroLli
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.Token
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.RRIStatement
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.RIStatement
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroOr
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroRet
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.DirectiveFillImmediate
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.syntaxTree.DirectiveFillString
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroAnd
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroBne
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroPop
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroCall
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroNot
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroMov
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroSubi
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroPush
    io.cuttlefish.parsing.StatementRegistry ..> io.cuttlefish.parsing.macros.MacroSyscall
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroCall
    io.cuttlefish.parsing.macros.MacroCall ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroCall ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroCall ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroCall ..> io.cuttlefish.parsing.macros.MacroMovi
    io.cuttlefish.parsing.macros.MacroCall ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.parsing.syntaxTree.Statement <|-- io.cuttlefish.parsing.macros.MacroNot
    io.cuttlefish.parsing.macros.MacroNot ..> io.cuttlefish.parsing.syntaxTree.Statement
    io.cuttlefish.parsing.macros.MacroNot ..> io.cuttlefish.parsing.syntaxTree.Argument
    io.cuttlefish.parsing.macros.MacroNot ..> io.cuttlefish.linking.RelocationType
    io.cuttlefish.parsing.macros.MacroNot ..> io.cuttlefish.parsing.syntaxTree.ParserContext
    io.cuttlefish.linking.SymbolTable ..> io.cuttlefish.linking.SymbolType
